# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: update and upgrade contianer image 
        run: | 
          git clone https://github.com/Harrison-S1/iboard.git
          cd iboard/
          cd /iboard
          cd CGI-4.51/; perl Makefile.PL; make; make install
          cd ../
          cd Date-EzDate-1.16/; perl Makefile.PL; make; make install
          a2enmod cgi
          mkdir -p /usr/lib/cgi-bin/ryansiob
          cd /iboard/ryansiob
          cp envelope.gif ryansiob.config.pl ryansiob.pl ryansiob.search.pl /usr/lib/cgi-bin/ryansiob/
          cd /usr/lib/cgi-bin/ryansiob/
          chown root:www-data envelope.gif
          chmod +x /usr/lib/cgi-bin/ryansiob/*
          cd /iboard/ryansiob
          mkdir -p /usr/local/ryansiob/
          cp allout.pl datafile /usr/local/ryansiob/
          chown -R root:www-data /usr/local/ryansiob/
          chmod -R 770 /usr/local/ryansiob/
          ln /usr/lib/cgi-bin/ryansiob/envelope.gif /var/www/html/
        # ARG DEBIAN_FRONTEND=noninteractive
        # ENV DEBIAN_FRONTEND="noninteractive" TZ="Europe/London"
          
        
#expose port 80 of the container
#EXPOSE 80

#start the container
#CMD ["apachectl", "-D", "FOREGROUND"]
